Lect2
Jagrmi-C/gostarted pull request #2
Opened 2020-04-13 22:08 UTC by Jagrmi-C

2020-04-14 14:57 UTC, ikamornikau requested changes
Please address the requested changes.

2020-04-14 14:57 UTC, ikamornikau commented on median/main.go
> +	if len(intsArr)%2 == 1 {
This `if ... else` clause is too long. I would prefer something like:
```
if len(intsArr)%2 == 1 {
        log...
        return float64(intsArr[val])
}

log...
return ...
```

2020-04-14 14:57 UTC, ikamornikau commented on median/main.go
> +	sort.Ints(intsArr)
If I added some `file.go` to the package and wanted to use `median()` func, I could miss the fact that the slice (`intsArr []int` - `median()` parameter) must be sorted. Please move you sorting inside `median()` func.

2020-04-14 14:57 UTC, ikamornikau commented on square/main.go
> +// Point is position in space
Please make your comment more clear:
```
// Point type represents a point in Cartesian coordinate system
```

2020-04-14 14:57 UTC, ikamornikau commented on square/main.go
> +	a     uint
Please add a comment to describe `a` variable.

2020-04-14 14:57 UTC, ikamornikau commented on square/main.go
> +// End - Point after made ...
Please make this comment more clear.

2020-04-14 14:57 UTC, ikamornikau commented on square/main.go
> +	endPoint := Point{newX, newY}
I would do something like:
```
return Point{
        x: s.start.x + int(s.a),
        y: s.start.y - int(s.a),
}
```

2020-04-14 14:57 UTC, ikamornikau commented on median/main.go
> +	intsArr := []int{7, 2, 4, 8, 1, 2, 9}
Please add one case for odd amount of slice elements.

2020-04-15 19:04 UTC, VolhaVetrava commented on median/main.go
> +		log.Println("Answer:", answer)
You're already printing the answer in the main function, so you don't really need to do it here as well, and then the variable `answer` is redundant and you can just return the value.

2020-04-15 19:04 UTC, VolhaVetrava commented on median/main.go
> +	log.Println("Answer:", answer)
Same as above

2020-04-16 08:34 UTC, VolhaVetrava requested changes

2020-04-16 08:34 UTC, VolhaVetrava commented on median/main.go
> +	answer = (float64(intsArr[val-1]) + float64(intsArr[val])) / 2
Variable answer is redundant, you can just write `return (float64(intsArr[val-1]) + float64(intsArr[val])) / 2`

2020-04-16 08:34 UTC, VolhaVetrava commented on median/main.go
> +		answer = float64(intsArr[val])
'Answer' is redundant, same as below

2020-05-06 16:31 UTC, closed without merging